name: Secrets Analysis

on: [ workflow_dispatch, push, pull_request ]

jobs:
  scanning:
    permissions:
      actions: read # for actions/checkout to fetch code
      contents: read # for actions/checkout to fetch code
      pull-requests: read
      security-events: write
    
    uses: ethicalakhilesh/Security/.github/workflows/Secrets.yml@Correcting-Secrets-Script-Path
